version: '3.8'
services:
  producer-service:
    build: src/main/java
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/stockdb
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
      - mongodb
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
